=== nvn18/2-2-lLAB_WORKS/__WEB TECHNOLOGIES__/LabCycle3/xml/data.dtd
<!ELEMENT data (sir+ , subject, name, des)>
<!ELEMENT sir (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT des (#PCDATA)>

=== nvn18/2-2-lLAB_WORKS/__WEB TECHNOLOGIES__/LabCycle3/xml/sir(ext dtd).xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE data SYSTEM "data.dtd">

<data>
   <sir type="sub1">
        <name>N.CHANDRA SEKHAR</name>
        <subject>WEB TECHNOLOGIES</subject>
        <des>ASST.PROFESSOR</des>
    </sir>

    <sir type="sub2">
        <name>N.CHANDRA SEKHAR</name>
        <subject>COMPUTER ORGANIZATION</subject>
        <des>ASST.PROFESSOR</des>
    </sir>

    <sir type="sub3">
        <name>N.CHANDRA SEKHAR</name>
        <subject>LOADING.....</subject>
        <des>ASST.PROFESSOR</des>
    </sir>
</data>
